name: TEST GITHUB

on:
  workflow_dispatch:


jobs:

  GITHUB-Test:
      runs-on: ubuntu-20.04
      steps:
      - uses: actions/checkout@v2
      - name: Prepare Packages/Kmods for Distribution
        id: distribution
        if: (!cancelled())
        env:
          API_TOKEN_GITHUB: '${{ secrets.API_TOKEN_GITHUB }}'
        run: |
          ls -al
          ls openwrt/bin
          chmod +x scripts/$GITHUB_RUN
          /bin/bash ${GITHUB_WORKSPACE}/scripts/github_run.sh
